#pragma once
#include <stdint.h>

/* One glyph of a 4-bit anti-aliased bitmap font (generated by tools/fontgen.c). */
typedef struct {
    uint16_t cp;   /* unicode code point */
    uint8_t w, h;  /* bitmap size in pixels */
    int8_t xo;     /* left bearing: bitmap x = pen_x + xo */
    int8_t yo;     /* bitmap top above baseline: bitmap y = baseline - yo */
    uint8_t adv;   /* horizontal advance */
    uint8_t _pad;
    uint32_t off;  /* offset into font bitmap, 4bpp high nibble first */
} font_glyph_t;

typedef struct {
    uint8_t px;       /* nominal pixel size */
    uint8_t line_h;   /* recommended line height */
    uint8_t ascent;   /* baseline distance from top of line */
    uint8_t descent;
    uint16_t count;
    const font_glyph_t *glyphs; /* sorted by code point */
    const uint8_t *bitmap;
} font_t;

#define FONT_COUNT 8
extern const font_t *const g_fonts[FONT_COUNT]; /* ascending sizes */

const font_glyph_t *font_glyph(const font_t *f, uint32_t cp);
int font_index_for_px(int px);
