/*
 * fontgen.c - converts a TTF/OTF font into the 4-bit anti-aliased bitmap
 * format used by the e-reader firmware (see main/font.h).
 *
 * Build (macOS / Homebrew):
 *   cc -O2 -o fontgen fontgen.c $(pkg-config --cflags --libs freetype2)
 *   # or: cc -O2 -I/opt/homebrew/include/freetype2 -L/opt/homebrew/lib -lfreetype fontgen.c -o fontgen
 * Build (Linux):
 *   sudo apt install libfreetype-dev && cc -O2 fontgen.c -o fontgen $(pkg-config --cflags --libs freetype2)
 *
 * Usage:
 *   ./fontgen <font.ttf> <pixel-size> <c-symbol-name> > out.c
 *
 * The generated file defines `const font_t <c-symbol-name>`.
 * Run tools/make_fonts.sh to regenerate every size shipped with the firmware.
 */
#include <ft2build.h>
#include FT_FREETYPE_H
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Unicode ranges baked into the firmware. Add more ranges here if you read
 * books in other scripts (each extra glyph costs flash in every size). */
static const unsigned RANGES[][2] = {
    {0x0020, 0x007E}, /* Basic Latin */
    {0x00A0, 0x017F}, /* Latin-1 Supplement + Latin Extended-A */
    {0x0192, 0x0192}, {0x0218, 0x021B}, {0x02C6, 0x02C7}, {0x02DC, 0x02DC},
    {0x0391, 0x03A9}, {0x03B1, 0x03C9}, /* Greek */
    {0x0400, 0x045F}, /* Cyrillic */
    {0x2010, 0x2015}, {0x2018, 0x201F}, {0x2020, 0x2022}, {0x2026, 0x2026},
    {0x2030, 0x2030}, {0x2039, 0x203A}, {0x20AC, 0x20AC}, {0x2116, 0x2116},
    {0x2122, 0x2122}, {0x2190, 0x2193}, {0x2212, 0x2212},
    {0x25B2, 0x25B2}, {0x25B6, 0x25B6}, {0x25BC, 0x25BC}, {0x25C0, 0x25C0},
    {0x25CF, 0x25CF}, {0x2713, 0x2713}, {0x2715, 0x2715}, {0xFFFD, 0xFFFD},
};

typedef struct {
    unsigned cp;
    int w, h, xo, yo, adv;
    unsigned off;
} glyph_t;

int main(int argc, char **argv)
{
    if (argc < 4) {
        fprintf(stderr, "usage: %s font.ttf px symbol\n", argv[0]);
        return 1;
    }
    const char *path = argv[1];
    int px = atoi(argv[2]);
    const char *sym = argv[3];

    FT_Library lib;
    FT_Face face;
    if (FT_Init_FreeType(&lib) || FT_New_Face(lib, path, 0, &face)) {
        fprintf(stderr, "cannot open font %s\n", path);
        return 1;
    }
    FT_Set_Pixel_Sizes(face, 0, px);

    int ascent = (int)((face->size->metrics.ascender + 63) >> 6);
    int descent = (int)((-face->size->metrics.descender + 63) >> 6);
    int line_h = (int)((face->size->metrics.height + 32) >> 6);
    if (line_h < ascent + descent) line_h = ascent + descent;

    glyph_t *glyphs = calloc(4096, sizeof(glyph_t));
    unsigned char *bits = malloc(4 << 20);
    unsigned nbits = 0;
    int n = 0;

    for (size_t r = 0; r < sizeof(RANGES) / sizeof(RANGES[0]); r++) {
        for (unsigned cp = RANGES[r][0]; cp <= RANGES[r][1]; cp++) {
            FT_UInt gi = FT_Get_Char_Index(face, cp);
            if (!gi) continue;
            if (FT_Load_Glyph(face, gi, FT_LOAD_RENDER | FT_LOAD_TARGET_LIGHT)) continue;
            FT_GlyphSlot s = face->glyph;
            FT_Bitmap *b = &s->bitmap;
            glyph_t *g = &glyphs[n++];
            g->cp = cp;
            g->w = (int)b->width;
            g->h = (int)b->rows;
            g->xo = s->bitmap_left;
            g->yo = s->bitmap_top;
            g->adv = (int)((s->advance.x + 32) >> 6);
            g->off = nbits;
            /* pack 4bpp, high nibble first, contiguous over the whole glyph */
            unsigned nib = 0;
            for (int y = 0; y < g->h; y++) {
                for (int x = 0; x < g->w; x++) {
                    unsigned v = b->buffer[y * b->pitch + x];
                    unsigned q = (v * 15 + 127) / 255;
                    if (nib & 1) bits[nbits + nib / 2] |= (unsigned char)q;
                    else bits[nbits + nib / 2] = (unsigned char)(q << 4);
                    nib++;
                }
            }
            nbits += (nib + 1) / 2;
        }
    }

    printf("/* Generated by tools/fontgen.c from %s at %dpx - do not edit.\n",
           strrchr(path, '/') ? strrchr(path, '/') + 1 : path, px);
    printf(" * DejaVu fonts: Bitstream Vera license (see tools/LICENSE). */\n");
    printf("#include \"font.h\"\n\n");
    printf("static const uint8_t s_bits[%u] = {\n", nbits ? nbits : 1);
    for (unsigned i = 0; i < nbits; i++) {
        printf("0x%02x,%s", bits[i], (i % 20 == 19) ? "\n" : "");
    }
    if (!nbits) printf("0");
    printf("\n};\n\n");
    printf("static const font_glyph_t s_glyphs[%d] = {\n", n);
    for (int i = 0; i < n; i++) {
        glyph_t *g = &glyphs[i];
        printf("{0x%04x,%d,%d,%d,%d,%d,0,%u},\n", g->cp, g->w, g->h, g->xo, g->yo, g->adv, g->off);
    }
    printf("};\n\n");
    printf("const font_t %s = {\n", sym);
    printf("    .px = %d, .line_h = %d, .ascent = %d, .descent = %d,\n", px, line_h, ascent, descent);
    printf("    .count = %d, .glyphs = s_glyphs, .bitmap = s_bits,\n", n);
    printf("};\n");

    fprintf(stderr, "%s: %dpx glyphs=%d bitmap=%u bytes line_h=%d\n", sym, px, n, nbits, line_h);
    FT_Done_Face(face);
    FT_Done_FreeType(lib);
    return 0;
}
